export const styleCampaign = {
    bg: {
        minHeight: "100vh",
        background: "none",
        pb: 4,
        display: "flex",
        flexDirection: "column",
        alignItems: "stretch",
        position: "relative",
    },
    bgGradient: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: -1,
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 60%, #f7971e 100%)",
        minHeight: "100vh",
        width: "100vw",
    },
    header: {
        background: "transparent",
        backdropFilter: "blur(10px)",
        borderBottom: "1px solid rgba(255,255,255,0.1)",
    },
    title: {
        fontWeight: 700,
        color: "white",
        textShadow: "0 2px 4px rgba(0,0,0,0.3)",
    },
    searchbar: {
        p: 2,
        mb: 3,
        borderRadius: 3,
        background: "rgba(255,255,255,0.95)",
        backdropFilter: "blur(10px)",
        boxShadow: "0 8px 32px rgba(0,0,0,0.1)",
    },
    tabs: {
        mb: 3,
        borderRadius: 3,
        background: "rgba(255,255,255,0.95)",
        backdropFilter: "blur(10px)",
        boxShadow: "0 8px 32px rgba(0,0,0,0.1)",
        overflow: "hidden",
    },
    card: (gradient, shadowColor) => ({
        height: "100%",
        minHeight: 320,
        width: 300,
        minWidth: 300,
        maxWidth: 300,
        display: "flex",
        flexDirection: "column",
        borderRadius: 3,
        background: gradient || "white",
        boxShadow: `0 8px 32px ${shadowColor || "rgba(0,0,0,0.1)"}`,
        transition: "all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
        position: "relative",
        overflow: "hidden",
        '&:hover': {
            transform: "translateY(-8px) scale(1.02)",
            boxShadow: `0 20px 40px ${shadowColor || "rgba(0,0,0,0.2)"}`,
        },
        '&::before': {
            content: '""',
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            height: "4px",
            background: `linear-gradient(90deg, ${shadowColor || "#667eea"}, transparent)`
        },
    }),
    cardTitle: {
        fontWeight: 700,
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        backgroundClip: "text",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        lineHeight: 1.3,
    },
    chip: {
        mb: 2,
        fontWeight: 600,
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    },
    address: {
        display: "flex",
        alignItems: "center",
        mb: 1.5,
        fontWeight: 500,
    },
    description: {
        display: "flex",
        alignItems: "flex-start",
        mb: 1.5,
        fontWeight: 400,
        displayWebkitBox: true,
        WebkitLineClamp: 2,
        WebkitBoxOrient: "vertical",
        overflow: "hidden",
    },
    deadline: {
        display: "flex",
        alignItems: "center",
        mb: 1,
        fontWeight: 500,
    },
    created: {
        display: "block",
        mt: 2,
        fontStyle: "italic",
        color: "#888",
    },
    empty: {
        p: 6,
        textAlign: "center",
        borderRadius: 3,
        background: "rgba(255,255,255,0.95)",
        backdropFilter: "blur(10px)",
        boxShadow: "0 8px 32px rgba(0,0,0,0.1)",
    },
    fab: {
        position: "fixed",
        bottom: 32,
        right: 32,
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        transition: "all 0.3s ease",
        boxShadow: "0 8px 32px rgba(102, 126, 234, 0.4)",
        '&:hover': {
            background: "linear-gradient(135deg, #5a67d8 0%, #6b46c1 100%)",
            transform: "scale(1.1)",
        },
    },
    dialogTitle: {
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        color: "white",
        fontWeight: 700,
    },
    dialogPaper: {
        borderRadius: 3,
        background: "rgba(255,255,255,0.95)",
        backdropFilter: "blur(20px)",
        boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
    },
};
